Luis Alejandro Ledesma Mujica
26/08/2024
A03 = Python

In [ ]:
import pandas as pd
datos = pd.read_excel("datosCT.xlsx")
datos["Utilidad"] = datos["Ingreso"] - datos ["Gasto"]
datos

Unnamed: 0  Ingreso  Gasto  Utilidad
0        Enero     1340   1880      -540
1      Febrero     2590   3130      -540
2        Marzo     3570   2140      1430
3        Abril     4450   3370      1080
4         Mayo     1330   2990     -1660
5        Junio     1610   1970      -360
6        Julio     1500   2230      -730
7       Agosto     2270   1240      1030
8   Septiembre     1910   1470       440
9      Octubre     2120   2280      -160
10   Noviembre     3950   1870      2080
11   Diciembre     1380   3140     -1760

In [ ]:
perdidas = datos [ datos ["Utilidad"]<0]
loses = perdidas ["Utilidad"].sum()
promediop = loses / 7
datos
print("El promedio de perdidas es: ", promediop,)

El promedio de perdidas es:  -821.4285714285714


In [ ]:
ingresostot = datos ["Ingreso"].sum()
ingresostot

28020

In [ ]:
import numpy as np
a = np.array([
    [1, 2],
    [3, 4]
])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([
    [2],
    [4]
])
b

array([[2],
       [4]])

In [ ]:
respuesta = np.dot(a, b)
respuesta

array([[10],
       [22]])